# Generated by Django 4.1.1 on 2022-09-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_entity_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='fim_contrato',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='inicio_contrato',
            field=models.DateTimeField(null=True),
        ),
    ]
