# Generated by Django 4.1.1 on 2022-09-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_entity_fim_contrato_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
