# Generated by Django 4.1.1 on 2022-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_entity_fim_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='fim_contrato',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='inicio_contrato',
            field=models.DateTimeField(default=False),
        ),
    ]
