# Generated by Django 4.1.1 on 2022-09-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="usuario",
            new_name="user",
        ),
    ]
