# Generated by Django 4.1.1 on 2022-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_entity_fim_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='fim_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='inicio_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
