# Generated by Django 4.1.1 on 2022-09-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_entity_fim_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='fim_contrato',
            new_name='end_contract',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='inicio_contrato',
            new_name='start_contract',
        ),
    ]
