# Generated by Django 4.1.1 on 2022-09-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_delete_entity"),
        ("entity", "0004_rename_fim_contrato_entity_end_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
            ),
            preserve_default=False,
        ),
    ]
